#' Add 10X Metrics to Object
#'
#' @description Add 10X Metrics to an object
#'
#' @param object An object
#' @param Metrics 10X Metrics generated by `Read10XMetrics` function
#' @param ... Additional arguments passed to methods
#'
#' @return Object with 10X Metrics added
#' @export
Add10XMetrics <- function(object, Metrics, ...) {
  UseMethod("Add10XMetrics")
}

#' Add Sample metadata to Object
#'
#' @description Add Sample metadata to an object
#'
#' @param object An object
#' @param merge_by_object Object column name to merge by
#' @param SampleMeta Data Frame containing Sample metadata
#' @param merge_by_meta Sample metadata column name to merge by
#' @param ... Additional arguments passed to methods
#'
#' @return Object with Sample metadata added
#' @export
AddSampleMeta <- function(object, merge_by_object = "orig.ident", SampleMeta, merge_by_meta, ...) {
  UseMethod("AddSampleMeta")
}


#' Convert Data to BPCells Format
#'
#' Convert Seurat or dgCMatrix objects to BPCells format for efficient storage and manipulation
#'
#' @param object An object to be converted
#' @param BPdir Directory path to store BPCells data. Default is `./BPCellData/`
#' @param assay Name of assay to use (for Seurat objects). Default is `RNA`
#' @param slot Name of slot to use (for Seurat objects). Default is `counts`
#' @param ... Additional arguments passed to methods
#' @return
#' **For Seurat object**:
#'     Returns a Seurat object with the specified assay and slot updated to BPCells format.
#'
#' **For dgCMatrix object**:
#'     Returns a BPCells matrix object.
#'
#' @examples
#' \dontrun{
#' # For Seurat object
#' seurat_obj <- ConvertToBPCells(seurat_obj)
#'
#' # For dgCMatrix
#' obj <- ConvertToBPCells(dgcmatrix_obj)
#' }
#'
#' @export
ConvertToBPCells <- function(object, ...) {
  UseMethod("ConvertToBPCells")
}



#' @title RunVarExplained Per-Feature Variance Explained by Variables
#'
#' @description
#' This function calculates the percentage of variance explained by one or more variables of interest for each feature. It supports both RNA and ADT assays and can handle sparse matrices efficiently. The function is designed to work with Seurat objects and can also accept raw matrices or metadata directly.
#'
#' @param object A Seurat object, a sparse matrix (`dgCMatrix`), `IterableMatrix`, or a dense matrix (`matrix`). If a Seurat object is provided, the function will extract the specified assay data (RNA or ADT) and normalize it if necessary.
#' @param assay Character string specifying the assay to use. Options are `"RNA"` (default) or `"ADT"`. If `"RNA"`, the function will normalize the data using `Seurat::NormalizeData`. If `"ADT"`, the function will normalize the data using CLR normalization.
#' @param variables A character vector specifying the variables of interest from the metadata. These variables will be used to explain the variance for each feature.
#' @param metadata A data frame or matrix containing the metadata. If `object` is a Seurat object, this parameter is optional, and the metadata will be extracted from `object@meta.data`. If `object` is a matrix-like, this parameter is required.
#' @param ... Additional arguments passed to the underlying variance calculation function.
#'
#' @return
#' A matrix containing the percentage of variance explained for each feature by the specified variables. The rows correspond to features, and the columns correspond to the variables of interest.
#'
#' @details
#' The function first checks the type of input object (`Seurat`, `dgCMatrix`, `IterableMatrix` or `matrix`) and processes it accordingly. For Seurat objects, it extracts the specified assay data and normalizes it if necessary. For sparse or dense matrices, it converts the data into an `IterableMatrix` format for efficient computation.
#'
#' @export
RunVarExplained <- function(object, ...) {
  UseMethod("RunVarExplained")
}

#' Convert an object to a SingleCellExperiment
#'
#' This function converts an input object (e.g., Seurat, matrix-like, or SingleCellExperiment)
#' into a SingleCellExperiment object. If the input is already a SingleCellExperiment,
#' it is returned as-is. For Seurat objects, the specified assay and slot are used for
#' conversion. For other objects (e.g., matrices), they are wrapped into a
#' SingleCellExperiment object.
#'
#' @param object The input object to convert. Can be a Seurat object, SingleCellExperiment
#'               object, or a matrix-like object.
#' @param assay The name of the assay to extract from the Seurat object (default: "RNA").
#'              Only applicable when `object` is a Seurat object.
#' @param slot The slot to extract from the Seurat object (default: "counts").
#'             Only applicable when `object` is a Seurat object.
#' @param ... Additional arguments passed to the conversion method.
#'
#' @return A SingleCellExperiment object.
#' @export
ConvertToSCE <- function(object, ...) {
  UseMethod("ConvertToSCE")
}


ConvertToSeurat <- function(object, ...) {
  UseMethod("ConvertToSeurat")
}



#  Not displayed ----------------------------------------------------------

getSampleName <- function(object, sample.by,  ...) {
  UseMethod("getSampleName")
}

splitObject <- function(object, split.by = "orig.ident", ...){
  UseMethod("splitObject")
}

#' @method splitObject Seurat
splitObject.Seurat <- function(object, split.by = "orig.ident", assay=NULL,tmpdir= "./temp/SingleCellMQC_tempBPCellSplitSeurat/",  ...){
  if(!is.null(split.by)){
    if(  length(unique(object@meta.data[[split.by]]))>1  ){
      message( paste0(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "-------- Split Seurat Object"))
      split_object <- .splitObjectSeurat(object, split.by = split.by, assay=assay, tmpdir=tmpdir)
    }else{
      split_object <- list(Sample = object)
      names(split_object) <- as.character(unique(object@meta.data[[split.by]]))
    }
  }else{
    split_object <- list(Sample = object)
  }
  return(split_object)
}

#' @method splitObject Seurat
splitObject.list <- function(object, split.by = NULL, ...){
  return(object)
}


# Get expression matrix
getMatrix <- function(object, ...) {
  UseMethod("getMatrix")
}

# Get cell metadata (supports Seurat and SingleCellExperiment formats)
getMetaData <- function(object, ...) {
  UseMethod("getMetaData")
}



#' @method getMatrix Seurat
getMatrix.Seurat <- function(object, assay = "RNA", slot = "counts", ...) {
  mat <- SeuratObject::GetAssayData(object = object, assay = assay, slot = slot)
  return(mat)
}

#' @method getMatrix dgCMatrix
getMatrix.dgCMatrix <- function(object, assay = "RNA", slot = "counts", ...) {
  return(object)
}

#' @method getMatrix IterableMatrix
getMatrix.IterableMatrix <- function(object, assay = "RNA", slot = "counts", ...) {
  return(object)
}



# Seurat method
#' @method getMetaData Seurat
getMetaData.Seurat <- function(object, ...) {
  meta <- object@meta.data
  return(meta)
}


GetMatrix <- function(object, ...){
  mat <- getMatrix(object, ...)
  return(mat)
}
