


# ##############################################################################
# #
# #  Data Add Functions
# #
# ##############################################################################

#' Add 10X Metrics to Object
#'
#' @description Add 10X Metrics to an object
#'
#' @param object An object
#' @param Metrics 10X Metrics generated by `Read10XMetrics` function
#' @param ... Additional arguments passed to methods
#'
#' @return Object with 10X Metrics added
#' @export
Add10XMetrics <- function(object, Metrics, ...) {
  UseMethod("Add10XMetrics")
}
#' @rdname Add10XMetrics
#' @method Add10XMetrics Seurat
#' @export
Add10XMetrics.Seurat <- function(object, Metrics, ...) {
  object@misc$SingleCellMQC$perQCMetrics$perSample$Metrics_10x <- Metrics
  return(object)
}

#' @rdname Add10XMetrics
#' @method Add10XMetrics default
#' @export
Add10XMetrics.default <- function(object, Metrics, ...) {
  stop("Add10XMetrics is not implemented for objects of class ", class(object))
}


#' Add Sample metadata to Object
#'
#' @description Add Sample metadata to an object
#'
#' @param object An object
#' @param merge_by_object Object column name to merge by
#' @param SampleMeta Data Frame containing Sample metadata
#' @param merge_by_meta Sample metadata column name to merge by
#' @param ... Additional arguments passed to methods
#'
#' @return Object with Sample metadata added
#' @export
AddSampleMeta <- function(object, merge_by_object = "orig.ident", SampleMeta, merge_by_meta, ...) {
  UseMethod("AddSampleMeta")
}
#' @rdname AddSampleMeta
#' @method AddSampleMeta Seurat
#' @export
AddSampleMeta.Seurat <- function(object, merge_by_object = "orig.ident", SampleMeta, merge_by_meta, ...) {
  metadata <- SampleMeta[match(object@meta.data[[merge_by_object]],
                               SampleMeta[[merge_by_meta]]), ]
  rownames(metadata) <- rownames(object@meta.data)
  metadata <- metadata[,-(match(merge_by_meta, colnames(SampleMeta))), drop=F]
  object <- SeuratObject::AddMetaData(object = object, metadata = metadata)
  return(object)
}

#' @rdname AddSampleMeta
#' @method AddSampleMeta default
#' @export
AddSampleMeta.default <- function(object, merge_by_object = "orig.ident", SampleMeta, merge_by_meta, ...) {
  stop("AddSampleMeta is not implemented for objects of class ", class(object))
}


# ##############################################################################
# #
# #  OBJECT CONVERSION FUNCTIONS (BETWEEN DIFFERENT OBJECT TYPES)
# #
# ##############################################################################

#' Convert Data to BPCells Format
#'
#' Convert Seurat or dgCMatrix objects to BPCells format for efficient storage and manipulation
#'
#' @param object An object to be converted
#' @param BPdir Directory path to store BPCells data. Default is `./BPCellData/`
#' @param assay Name of assay to use (for Seurat objects). Default is `RNA`
#' @param slot Name of slot to use (for Seurat objects). Default is `counts`
#' @param ... Additional arguments passed to methods
#' @return
#' **For Seurat object**:
#'     Returns a Seurat object with the specified assay and slot updated to BPCells format.
#'
#' **For dgCMatrix object**:
#'     Returns a BPCells matrix object.
#'
#' @examples
#' \dontrun{
#' # For Seurat object
#' seurat_obj <- ConvertToBPCells(seurat_obj)
#'
#' # For dgCMatrix
#' obj <- ConvertToBPCells(dgcmatrix_obj)
#' }
#'
#' @export
ConvertToBPCells <- function(object, ...) {
  UseMethod("ConvertToBPCells")
}
#' @rdname ConvertToBPCells
#' @method ConvertToBPCells Seurat
#' @export
ConvertToBPCells.Seurat <- function(object, BPdir="./BPCellData/", assay = "RNA", slot="counts", ...) {
  BPdir <- paste0(BPdir, "/", assay)
  data <- Seurat::GetAssayData(object, assay = assay, slot = slot)
  BPCells::write_matrix_dir(data, dir = BPdir, overwrite = TRUE)
  data <- BPCells::open_matrix_dir(BPdir)
  object <- SeuratObject::SetAssayData(object = object,
                                       assay = assay,
                                       slot = slot,
                                       new.data = data)
  return(object)
}

#' @rdname ConvertToBPCells
#' @method ConvertToBPCells dgCMatrix
#' @export
ConvertToBPCells.dgCMatrix <- function(object, BPdir="./BPCellData/", ...) {
  BPCells::write_matrix_dir(object, dir = BPdir, overwrite = TRUE)
  data <- BPCells::open_matrix_dir(BPdir)
  return(data)
}


#' @rdname ConvertToBPCells
#' @method ConvertToBPCells IterableMatrix
#' @export
ConvertToBPCells.IterableMatrix <- function(object, BPdir="./BPCellData/", ...) {
  BPCells::write_matrix_dir(object, dir = BPdir, overwrite = TRUE)
  data <- BPCells::open_matrix_dir(BPdir)
  return(data)
}





#' Convert an object to a SingleCellExperiment
#'
#' This function converts an input object (e.g., Seurat, matrix-like, or SingleCellExperiment)
#' into a SingleCellExperiment object. If the input is already a SingleCellExperiment,
#' it is returned as-is. For Seurat objects, the specified assay and slot are used for
#' conversion. For other objects (e.g., matrices), they are wrapped into a
#' SingleCellExperiment object.
#'
#' @param object The input object to convert. Can be a Seurat object, SingleCellExperiment
#'               object, or a matrix-like object.
#' @param assay The name of the assay to extract from the Seurat object (default: "RNA").
#'              Only applicable when `object` is a Seurat object.
#' @param slot The slot to extract from the Seurat object (default: "counts").
#'             Only applicable when `object` is a Seurat object.
#' @param ... Additional arguments passed to the conversion method.
#'
#' @return A SingleCellExperiment object.
#' @export
ConvertToSCE <- function(object, ...) {
  UseMethod("ConvertToSCE")
}
#' @rdname ConvertToSCE
#' @method ConvertToSCE Seurat
#' @export
ConvertToSCE.Seurat <- function(object, assay="RNA", slot="counts", ...) {
  x <- suppressWarnings(Seurat::as.SingleCellExperiment(object, assay = assay, slot = slot))
  return(x)
}

#' @rdname ConvertToSCE
#' @method ConvertToSCE SingleCellExperiment
#' @export
ConvertToSCE.SingleCellExperiment <- function(object, ...) {
  return(object)
}

#' @rdname ConvertToSCE
#' @method ConvertToSCE default
#' @export
ConvertToSCE.default <- function(object, ...) {
  x <- SingleCellExperiment::SingleCellExperiment(assays = list(counts = object))
  return(x)
}




ConvertToSeurat <- function(object, ...) {
  UseMethod("ConvertToSeurat")
}
#' @method ConvertToSeurat list
ConvertToSeurat.list <- function(object, ...) {
  if (!("Gene Expression" %in% names(object))) {
    stop("Input list must contain a 'Gene Expression' component.")
  }

  # Create Seurat object from "Gene Expression"
  rna <- Seurat::CreateSeuratObject(object$`Gene Expression`, min.cells = 1, ...)

  # Add "Antibody Capture" as an additional assay if present
  if ("Antibody Capture" %in% names(object)) {
    if ("Assay5" %in% class(rna@assays$RNA)) {
      adt <- SeuratObject::CreateAssay5Object(object$`Antibody Capture`, min.cells = 1, ...)
    } else {
      adt <- SeuratObject::CreateAssayObject(object$`Antibody Capture`, min.cells = 1, ...)
    }
    rna[["ADT"]] <- adt
    Seurat::DefaultAssay(rna) <- "RNA"
  }

  return(rna)
}

#' @method ConvertToSeurat default
ConvertToSeurat.default <- function(object, ...) {
  Seurat::CreateSeuratObject(object, min.cells = 1, ...)
}

#' @method ConvertToSeurat Seurat
ConvertToSeurat.Seurat <- function(object, ...) {
  return(object)
}



#  Not displayed ----------------------------------------------------------


# ##############################################################################
# #
# #  Split Object
# #
# ##############################################################################

.splitObjectSeurat <- function(object, assay=NULL, split.by="orig.ident", tmpdir= "./temp/SingleCellMQC_tempBPCellSplitSeurat/"){
  if(is.null(assay)){
    assay_names <- SeuratObject::Assays(object)
  }else{
    assay_names = assay
  }

  metalist <- split(object@meta.data, as.character(object@meta.data[[split.by]]) )
  exp_list <- lapply(assay_names, function(assay_name) {
    counts <- SeuratObject::GetAssayData(object, assay = assay_name, slot = "counts")
    return(counts)
  })

  names(exp_list) <- assay_names

  if (is(exp_list[[1]], "IterableMatrix")) {
    # Check if the folder exists, and create it if it doesn't
    if (!dir.exists(tmpdir)) {
      dir.create(tmpdir, recursive = TRUE)
      message("BPCells Temp folder created: ", tmpdir)
    } else {
      message("BPCells Temp folder already exists: ", tmpdir)
    }
  }
  rm(object)
  ## Run parallel processing
  # progressr::with_progress({
  p <- progressr::progressor(along = 1:(length(metalist)+1) )
  object_list <- smart_lapply(metalist, function(x) {
    cell_name <- rownames(x)
    # first
    subexp <- exp_list[[ assay_names[1] ]][, cell_name, drop = FALSE]
    if (is(subexp, "IterableMatrix")) {
      subexp <- suppressWarnings(suppressMessages(
        BPCells::write_matrix_dir(subexp, tempfile("mat", tmpdir = tmpdir))
      ))
    }
    subObject <- suppressWarnings(suppressMessages(
      SeuratObject::CreateSeuratObject(subexp, meta.data = x, assay = assay_names[1])
    ))


    if (length(assay_names) > 1) {
      is_assay5 <- "Assay5" %in% class(subObject[[assay_names[1]]])

      exp_matrices <- lapply(seq_along(assay_names[-1]), function(i) {
        ## check matrix exist
        len <- length(intersect(cell_name, colnames(exp_list[[assay_names[-1][i]]])))
        if( len == 0  ){
          return(NULL)
        }
        tempexp <- exp_list[[assay_names[-1][i]]][, cell_name, drop = FALSE]
        if (is(tempexp, "IterableMatrix")) {
          tempexp = BPCells::write_matrix_dir(tempexp, tempfile("mat", tmpdir = tmpdir))
        }
        return(tempexp)
      })
      for (i in seq_along(assay_names[-1])) {
        ## check assay
        if(!is.null(exp_matrices[[i]])){
          subObject[[assay_names[-1][i]]] <- if (is_assay5) {
            SeuratObject::CreateAssay5Object(exp_matrices[[i]])
          } else {
            SeuratObject::CreateAssayObject(exp_matrices[[i]])
          }
        }
      }

      Seurat::DefaultAssay(subObject) <- assay_names[1]
    }
    p()
    return(subObject)
  }
  ,
  future.packages = c("BPCells"), future.seed = NULL
  )
  # }
  # ,handlers=  progressr::handlers(progressr::handler_progress(
  #   format = ":spin :bar :percent :elapsed :eta",
  #   clear = FALSE
  # ))
  # )
  rm(exp_list)
  return(object_list)
}




splitObject <- function(object, split.by = "orig.ident", ...){
  UseMethod("splitObject")
}

#' @method splitObject Seurat
splitObject.Seurat <- function(object, split.by = "orig.ident", assay=NULL,tmpdir= "./temp/SingleCellMQC_tempBPCellSplitSeurat/",  ...){
  if(!is.null(split.by)){
    if(  length(unique(object@meta.data[[split.by]]))>1  ){
      message( paste0(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "-------- Split Seurat Object"))
      split_object <- .splitObjectSeurat(object, split.by = split.by, assay=assay, tmpdir=tmpdir)
    }else{
      split_object <- list(Sample = object)
      names(split_object) <- as.character(unique(object@meta.data[[split.by]]))
    }
  }else{
    split_object <- list(Sample = object)
  }
  return(split_object)
}

#' @method splitObject Seurat
splitObject.list <- function(object, split.by = NULL, ...){
  return(object)
}

# ##############################################################################
# #
# #  GETTING DATA FROM OBJECTS
# #
# ##############################################################################

getSampleName <- function(object, sample.by,  ...) {
  UseMethod("getSampleName")
}
#' @method getSampleName Seurat
getSampleName.Seurat <- function(object, sample.by="orig.ident", ...) {
  return(unique(object@meta.data[[sample.by]]) )
}

GetMatrix <- function(object, ...){
  mat <- getMatrix(object, ...)
  return(mat)
}
# Get expression matrix
getMatrix <- function(object, ...) {
  UseMethod("getMatrix")
}
#' @method getMatrix Seurat
getMatrix.Seurat <- function(object, assay = "RNA", slot = "counts", ...) {
  mat <- SeuratObject::GetAssayData(object = object, assay = assay, slot = slot)
  return(mat)
}
#' @method getMatrix dgCMatrix
getMatrix.dgCMatrix <- function(object, assay = "RNA", slot = "counts", ...) {
  return(object)
}
#' @method getMatrix IterableMatrix
getMatrix.IterableMatrix <- function(object, assay = "RNA", slot = "counts", ...) {
  return(object)
}


# Get cell metadata (supports Seurat and SingleCellExperiment formats)
getMetaData <- function(object, ...) {
  UseMethod("getMetaData")
}
# Seurat method
#' @method getMetaData Seurat
getMetaData.Seurat <- function(object, ...) {
  meta <- object@meta.data
  return(meta)
}
# default method
#' @method getMetaData default
getMetaData.default <- function(object, ...) {
  meta <- object
  return(meta)
}




